#############  Navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Startups"
url = "/startups"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3


[[main]]
name = "Founder"
url = "/about"
weight = 4

#[[main]]
#weight = 5
#name = "Pages"

#[[main]]
#parent = "Pages"
#name = "Elements"
#url = "/elements"

# [[main]]
# parent = "Pages"
# name = "Contacto"
# url = "/contacto"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categorías"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "Founder"
url = "/about"
weight = 2

[[footer]]
name = "Blog"
url = "/blog"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
